### ISSUE TITLE
Slight tweak (improvement?) to Makefile.local

### ISSUE THREAD

**Issue by ctotheameron** [stathis-alexander/solargraph-zeitwork-script#1]
https://github.com/stathis-alexander/solargraph-zeitwork-script/blob/fc17d9dbbaa9fe8e725048ad47b49b64c4265cac/Makefile.local#L3

Doing:

```
find a_list config lib app packages -type d -print0 | xargs -0 ./vscode-solargraph/generate_modules.rb
```

Gave me a more exhaustive pull of namespaces without having to manually enumerate everything.

**Comment by stathis-alexander** [comment]
Hm. That doesn't quite seem to work. That seems to flatten all the folder into namespaces. That gets me a bunch of empty files, synthetic services that aren't actually namespaces, and the hierarchal structure of the modules is lost. 

For instance, for the folder `app/services/venture/comptroller_exports`, I get
```
vscode-solargraph
  app/
    services/
      venture/
        comptroller_exports.rb
      venture.rb
    services.rb
  app.rb
```
The file `app.rb` contains 
```
Module Services
  Module Venture
    Module ComptrollerExports
    end
  end
end
```
, while `comptroller_exports.rb` was blank (other than the comment), and `venture.rb` contains
```
module ComptrollerExports; end
```
not `module Venture; module ComptrollerExports; end; end` as you'd expect.


We could definitely make some sort of auto-generated list of folders like this work, but we'd have to modify our generate_namespaces.

**Comment by stathis-alexander** [comment]
I think it would be cool if we could do this however:
1. auto-generate a list of folders/namespaces by scanning the root folder for things
2. 'co-locate' the module files: `app/services/venture/comptroller_exports` would generate `vscode-solargraph/app/services/venture/comptroller_exports.rb` which would contain:
```
module Venture
  module ComptrollerExports
  end
end
```
rather than a single `app/services.rb` which contains main top-level namespaces.

**Comment by ctotheameron** [comment]
Ah yeah I'm misunderstanding how this whole thing works heh. Noticed the empty files but VSCode seemed to be working.

My b :)

**Comment by ctotheameron** [comment]
Just curious - I went back and checked the behavior in VSCode with ComptrollerExports and hover/clickthrough work for me. 

I get that the exported module defs are kinda borked, but it still seems to be working for me in practice.

Is there something "functionally" broken with my approach? 

https://user-images.githubusercontent.com/3002968/174688280-9d7460d8-238d-4801-916a-68ecdc068d97.mp4

<img width="591" alt="Screen Shot 2022-06-20 at 6 21 26 PM" src="https://user-images.githubusercontent.com/3002968/174688311-5562f044-cd8f-49c0-b17e-aacdc2426748.png">


BTW! Thanks for figuring this out. Loving having my solargraph working again. I don't remember when I noticed it broke, but this is a lifesaver!

**Comment by stathis-alexander** [comment]
Yes - it does work, but it generates far more files than you need and many of the files it creates are unused/empty. My namespaces/classes in the services directory all point to `services.rb`, for instance. Not a huge deal, but sort of a horizontal move in some sense. I'm sure there's some way to combine both approaches to do something slightly more clever and better.
