### ISSUE TITLE
Slight tweak to generate_modules.rb

### ISSUE THREAD

**Issue by ctotheameron** [stathis-alexander/solargraph-zeitwork-script#2]
https://github.com/stathis-alexander/solargraph-zeitwork-script/blob/fc17d9dbbaa9fe8e725048ad47b49b64c4265cac/vscode-solargraph/generate_modules.rb#L63

I found that when running this in the root dir, the files were splatting out at root. 

Tweaked locally to:

```
  File.open(file_path, "w") do |file|
```

**Comment by stathis-alexander** [comment]
Ah, yes. I must have fixed this locally and not committed. Thanks!
